version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  postgres:
    image: 'postgres:9.6'
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - 'sentry-postgres:/var/lib/postgresql/data'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    restart: always
    image: 'redis:5.0.9'
    volumes:
      - 'sentry-redis:/data'

volumes:
  cnpm-files-volume:
  cnpm-db-volume:
  sentry-postgres:
  sentry-redis:
